name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 4.242.16.29
          username: ernany
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/suavitrine

            echo "➡️ Parando container antigo"
            docker compose down frontend || true

            echo "➡️ Atualizando frontend via subtree"
            git fetch frontend
            git subtree pull --prefix=frontend frontend main --squash

            echo "➡️ Limpando dist antigo"
            sudo rm -rf frontend/dist

            echo "➡️ Instalando dependências"
            cd frontend
            npm ci --legacy-peer-deps

            echo "➡️ Buildando frontend"
            npm run build

            cd ..

            echo "➡️ Subindo container Nginx com novo build"
            docker compose up -d frontend
