name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 4.242.16.29
          username: ernany
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/suavitrine
            git fetch frontend
            git subtree pull --prefix=frontend frontend main --squash
            cd frontend
            rm -rf dist
            chmod -R 755 dist
            npm ci
            npm run build
            cd ..
            docker compose down frontend -v
            docker compose up -d frontend
